Fixing transaction list issue after recovery
firoorg/firo pull request #1017
Opened 2021-04-19 06:32 UTC by levonpetrosyan93

2021-04-20 08:59 UTC, a-bezrukov approved these changes

2021-04-27 10:12 UTC, psolstice requested changes
Could you please write a short description what was a problem in the first place?

2021-04-27 10:16 UTC, reubenyap commented
When recovering the wallet with a mnemonic, transactions list has empty 0.0000 FIRO entries. 

![image](https://user-images.githubusercontent.com/22736605/116225469-77102300-a784-11eb-9b88-2ed78d9af724.png)

![image](https://user-images.githubusercontent.com/22736605/116225495-80998b00-a784-11eb-93ab-3603ccbd83aa.png)

2021-04-29 09:31 UTC, psolstice approved these changes

2021-04-29 11:22 UTC, merged