Remove unnecessary zero checks from Lelantus protocol
firoorg/firo pull request #1019
Opened 2021-04-27 14:31 UTC by AaronFeickert

Removes unnecessary zero checks from range and one-of-many proof verifiers.

2021-05-07 10:10 UTC, reubenyap commented
Test failing please kindly resolve lelantus_mintspend.py

2021-06-14 12:56 UTC, levonpetrosyan93 approved these changes

2021-06-24 18:21 UTC, levonpetrosyan93 submitted a review, later dismissed

2021-07-07 07:56 UTC, levonpetrosyan93 approved these changes

2021-07-08 09:29 UTC, levonpetrosyan93 approved these changes

2021-07-11 14:43 UTC, levonpetrosyan93 approved these changes

2021-07-13 18:16 UTC, levonpetrosyan93 approved these changes

2021-07-15 16:21 UTC, levonpetrosyan93 approved these changes

2021-07-16 09:03 UTC, psolstice requested changes
Technically it's a hard fork. Thus proper management of block number is needed and checks should be dropped only after specific block. Otherwise it's possible to create a transaction which causes forks in our network shortly after rolling out the update. Given that these checks are relatively fast I don't think it's worth it

2021-07-16 12:10 UTC, closed without merging