Replace balance verification with multiscalar multiplication operations
firoorg/firo pull request #1037
Opened 2021-05-21 19:59 UTC by AaronFeickert

Updates balance proof verification to use multiscalar multiplication operations where applicable.

Review requested.

2021-06-21 12:56 UTC, levonpetrosyan93 requested changes
The idea is good, but I will suggest to leave computation of `A` as is, as previously it was doing `Cout.size()` times additions and one multiplication, but now it is doing several multiplications,
I tried to test, and in my setup I got this 716 for old version, 491 for your case, and 400 in case what I am suggesting, numbers are in clock ticks.

2021-06-21 16:11 UTC, AaronFeickert commented
> The idea is good, but I will suggest to leave computation of `A` as is, as previously it was doing `Cout.size()` times additions and one multiplication, but now it is doing several multiplications,
> I tried to test, and in my setup I got this 716 for old version, 491 for your case, and 400 in case what I am suggesting, numbers are in clock ticks.

Updated.

2021-06-21 19:54 UTC, levonpetrosyan93 approved these changes

2021-06-22 14:00 UTC, psolstice approved these changes

2021-06-22 16:01 UTC, merged