Adding private balance value into getBalance rpc result
firoorg/firo pull request #1045
Opened 2021-06-21 14:51 UTC by levonpetrosyan93

2021-06-28 11:14 UTC, a-bezrukov approved these changes

2021-07-01 05:30 UTC, psolstice requested changes
My suggestion is instead of modifying existing RPC (and losing ability to get transparent balance with RPC call) we add another RPC to get private balance

2021-07-05 14:58 UTC, psolstice approved these changes

2021-07-05 15:52 UTC, a-bezrukov approved these changes

2021-07-05 15:52 UTC, merged