Increasing weight limit for Lelantus joinsplit tx
firoorg/firo pull request #1061
Opened 2021-08-09 14:17 UTC by levonpetrosyan93

2021-08-10 12:12 UTC, a-bezrukov requested changes

2021-08-10 12:40 UTC, a-bezrukov approved these changes

2021-08-12 19:08 UTC, levonpetrosyan93 commented on src/consensus/params.h
> +    int nLelantusV3PayloadStartBlock;
Yes, correct, we need to merge this PR after merging payload PR.

2021-08-17 09:01 UTC, psolstice approved these changes

2021-08-17 15:12 UTC, merged