Is lelantus
firoorg/firo pull request #1062
Opened 2021-08-09 14:18 UTC by a-bezrukov

## PR intention
Introduces the Instantsend functionality which is capable of working with Lelantus

## Code changes brief
Lelantus jsplits are locked based on their coin serial numbers

2021-08-30 14:07 UTC, psolstice requested changes

2021-09-27 05:45 UTC, a-bezrukov commented on src/llmq/quorums_chainlocks.cpp
> +    if (chainActive.Height() <= Params().GetConsensus().nInstantSendBlockFilteringStartHeight) {
Fixed, thanks!

2021-09-29 09:05 UTC, psolstice requested changes

2021-09-29 09:05 UTC, psolstice commented on src/llmq/quorums_chainlocks.cpp
> +    if (chainActive.Height() <= Params().GetConsensus().nInstantSendBlockFilteringStartHeight) {
something went wrong and both < and <= checks are there

2021-09-29 14:56 UTC, psolstice approved these changes

2021-09-29 17:30 UTC, levonpetrosyan93 approved these changes

2021-09-29 18:37 UTC, merged