Devnet chain
firoorg/firo pull request #1072
Opened 2021-09-24 16:10 UTC by psolstice

## PR intention
Create a new chain in addition to `mainnet`, `testnet` and `regtest`

## Code changes brief
New chain called `devnet` is added for developing new features ahead of what's running on `testnet`. Both chainlock and IS lock can be done there with 5_60 quorum (5 quorum members, 60% votes required for lock). Blockchain data is stored in `devnet` subdirectory of firo data directory. This chain is using ProgPoW from block one.

2021-09-26 16:25 UTC, levonpetrosyan93 commented
Please add `devnet` also in `GenerateNewKey() `function in wallet.cpp:199

2021-09-26 16:37 UTC, levonpetrosyan93 requested changes

2021-09-26 16:37 UTC, levonpetrosyan93 commented on src/chainparams.cpp
> +        for (const auto& str : lelantus::lelantus_testnet_blacklist) {
I think we don't need this here.

2021-09-27 14:51 UTC, psolstice commented on src/chainparams.cpp
> +        for (const auto& str : lelantus::lelantus_testnet_blacklist) {
thanks, copy-paste error

2021-09-28 15:13 UTC, levonpetrosyan93 approved these changes

2021-09-28 15:35 UTC, a-bezrukov approved these changes

2021-09-28 19:58 UTC, merged