Fixing the crashing issue on listaddressgroupings rpc
firoorg/firo pull request #1085
Opened 2021-11-15 15:26 UTC by firstcryptoman

2021-11-15 15:51 UTC, levonpetrosyan93 approved these changes

2021-11-18 13:46 UTC, a-bezrukov requested changes
Sorry, how does this fix a crash?

2021-11-18 14:34 UTC, levonpetrosyan93 commented
@a-bezrukov spend transaction types have no standard inputs so in case of spend we don't need to go inside if, but this call  `pcoin->tx->IsLelantusJoinSplit()` is added out of braces by mistake, me need to move it into braces, `HasNoRegularInputs()` function checkes it for all spend transactions.

2021-11-18 15:31 UTC, a-bezrukov approved these changes

2021-11-18 15:32 UTC, merged