Libspark fuzzing harness
firoorg/firo pull request #1340
Opened 2023-10-03 12:26 UTC by man2706kum

This PR includes fuzzing harness for libspark. The harness is inside src/fuzz/. The quick start guide can be found in src/fuzz/README.md

2023-10-16 00:54 UTC, levonpetrosyan93 commented on src/fuzz/fuzzing_utilities.cpp
> +        ge_vec.push_back(GetGroupElement());
resize creates len number of infinity GroupElements and pushes into ge_vec, and here we push len+1 number of GroupElements, is this function suppose to work that way?

2023-10-16 00:55 UTC, levonpetrosyan93 commented on src/fuzz/fuzzing_utilities.cpp
> +        ge_vec[i] = (GetMemberGroupElement());
i <= len will make loop go out of ge_vec's bound

2023-10-16 00:56 UTC, levonpetrosyan93 commented on src/fuzz/fuzzing_utilities.cpp
> +        scalar_vec.push_back(GetScalar());
the same here

2023-10-16 00:57 UTC, levonpetrosyan93 commented on src/fuzz/fuzzing_utilities.cpp
> +        scalar_vec.push_back(GetScalar());
same here

2023-10-16 00:57 UTC, levonpetrosyan93 commented on src/fuzz/fuzzing_utilities.cpp
> +        scalar_vec.push_back(GetScalar_modified());
same here

2023-10-16 01:05 UTC, levonpetrosyan93 commented on src/fuzz/libspark/aead_debug
please remove binary files

2023-10-27 10:19 UTC, psolstice requested changes

2023-10-27 10:19 UTC, psolstice commented on src/fuzz/libspark/aead_hfuzz
Please remove binary files. I assume these are built from the sources

2023-10-27 18:40 UTC, levonpetrosyan93 requested changes

2023-10-27 18:40 UTC, levonpetrosyan93 commented on src/fuzz/fuzzing_utilities.cpp
> +    for (int i = 0; i < len; i++) {
We don't need this loop, as ge_vec.resize(len) does the same, or do reserve() instead of resize().

2023-11-02 15:24 UTC, AaronFeickert requested changes

2023-11-02 15:24 UTC, AaronFeickert commented on src/fuzz/README.md
> +### Dependencies
This is missing several `boost` and `openssl` dependencies that are required for the build to succeed.

2023-11-02 15:24 UTC, AaronFeickert commented on src/fuzz/README.md
> +Follow the instructions from https://github.com/firoorg/firo/tree/spark#readme
This contradicts the `git clone` command in the next step.

2023-11-02 15:24 UTC, AaronFeickert commented on src/fuzz/README.md
> +git clone -b spark_fuzz_blog https://github.com/hashcloak/firo.git
This should be changed to the upstream repository.

2023-11-02 15:24 UTC, AaronFeickert commented on src/fuzz/README.md
> +hongfuzz -i <path_of_input_corpora>/<filename_inputs> -- ./<filename_hfuzz> ___FILE___
`s/hongfuzz/honggfuzz`

2023-11-02 15:24 UTC, AaronFeickert commented on src/fuzz/README.md
> +2. `hongfuzz -i ../../inputs/bpplus_inputs -- ./../../libspark/bpplus_hfuzz ___FILE___`
As above, `hongfuzz` is a typo. Also, the relative path to the instrumented binary is incorrect.

2023-11-02 15:24 UTC, AaronFeickert commented on src/fuzz/README.md
> +If there is no input corpora, empty corpora can be provided.
Please provide a note that this means creating and passing an empty directory via `-i`.

2023-11-06 11:12 UTC, levonpetrosyan93 approved these changes

2023-11-16 00:49 UTC, merged