add org.firo.firo-qt.metainfo.xml for flathub
firoorg/firo pull request #1415
Opened 2024-02-22 08:39 UTC by erciccione

Adding this file upstream, as asked by Flathub's team: https://github.com/flathub/flathub/pull/4932#discussion_r1484496323

2024-02-22 14:47 UTC, justanwar requested changes

2024-02-22 14:47 UTC, justanwar commented on contrib/flathub/org.firo.firo-qt.metainfo.xml
> +    https://github.com/firo/firo/issues/new?title=[flatpak]
Repo URL should be `firoorg/firo`

2024-02-23 09:54 UTC, erciccione commented on contrib/flathub/org.firo.firo-qt.metainfo.xml
> +    https://github.com/firo/firo/issues/new?title=[flatpak]
Fixed. Thanks

2024-02-23 17:58 UTC, justanwar approved these changes

2024-02-24 10:46 UTC, levonpetrosyan93 approved these changes

2024-02-26 09:05 UTC, merged