Add memo field in UI
firoorg/firo pull request #1493
Opened 2024-11-03 09:27 UTC by levoncrypto

2024-11-10 23:56 UTC, levonpetrosyan93 requested changes

2024-11-10 23:56 UTC, levonpetrosyan93 commented on src/spark/sparkwallet.cpp
> +        CRecipient recipient = {script, CAmount(outputs[i].v), false, addr, memo};
I think this is a useful suggestion. Better to apply this, use get_memo_bytes() to get the max memo size.

2024-11-10 23:56 UTC, levonpetrosyan93 commented on src/spark/primitives.h
> +        READWRITE(memo);
you need a check here, to prevent issues in case you have an old type data without this field .

2024-11-10 23:56 UTC, levonpetrosyan93 commented on src/qt/sendcoinsentry.cpp
> +    int maxLength = 256;
Hard coding numbers like this is wrong coding style, also this is not right number. use get_memo_bytes() function to get memo size limit.

2024-11-29 10:36 UTC, psolstice approved these changes

2024-11-29 18:58 UTC, levonpetrosyan93 approved these changes

2024-11-29 18:59 UTC, merged